language: c
sudo: false
compiler:
  - gcc
dist: trusty
os:
  - linux
  - osx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libjsoncpp-dev
    - libnlohmann-dev
    - libcap-dev
    - g++-5
cache:
  directories:
  - $HOME/libsodium

before_script:
  #installing libsodium, needed for Core
  - ./scripts/libsodium.sh
  - ./scripts/jsoncpp.sh
  #creating libraries links and updating cache
  #- sudo ldconfig > /dev/null
  # and toxcore
  - git clone git://github.com/TokTok/toxcore.git > /dev/null
  - cd toxcore
  - autoreconf -i
  - CFLAGS="-Ofast -Wall -Wextra" ./configure --enable-daemon --enable-ntox --with-libsodium-headers=${HOME}/libsodium/include/ --with-libsodium-libs=${HOME}/libsodium/lib/ --prefix=${HOME}/toxcore/
  - make -j3
  - make check
  - make install
  - cd ..

script:
  - mkdir build
  - cd build
  - export CXX=g++-5
  - cmake ../ -DSTATIC=1 -DTOX_PREFIX=${HOME}/toxcore/ -DSODIUM_PREFIX=${HOME}/libsodium/
  - g++-5 --version
  - CXX=g++-5 make

notification:
  email: false
